include ../../Makefile
# Add paths to dependency headers here
ExternalIncludes = -I../dependencies/include/
ExternalLibraries =

# Includes and objects
Objects = Matrix4_inverse.o
Includes = -I../../include
Libraries =
Defines = 

Version = $(VersionMajor).$(VersionMinor)
ExecutableName = matrix4
Executable = 1

include ../shared.makefile
