RootPath = ../..
Sources = Logger.cpp SettingsManager.cpp \
	  MurmurHash3.cpp
#	  SettingsManager.cpp HDFSettingsLoader.cpp ModelLoader.cpp \
#	  FileSystem.cpp HrenginShell.cpp \
Defines = AW_MODULE_CORE
Libraries = 
ProjectName = awcore
Executable = false

include $(RootPath)/Rules.mk
