#ifndef aw_tests_algorithm_sort_tests_h
#define aw_tests_algorithm_sort_tests_h

#include "tagged.h"

#include <aw/test/test.h>
#include <aw/ranges/value_range.h>

#include <algorithm>
#include <random>
#include <vector>

/*!
 * A set of tests that works for any sorting algorithm, that
 * needs only a callable that sorts a container in place.
 *
 * Register one with TestSortAlgorithm, passing the callable,
 * and optionally the class of sorting algorithm (stable or unstable):
 *
 *     TestSortAlgorithm(insertion_sort, [](auto& v) { insertion_sort(v.begin(), v.end()); })
 *     TestSortAlgorithm(std_sort, [](auto& v) { std::sort(v.begin(), v.end()); }, unstable)
 *
 * An algorithm registered as unstable is only checked for ordering; a stable
 * one is also checked for keeping equal elements in their original order.
 */
namespace aw::test_sort {
namespace {

enum order { stable, unstable };

/*!
 * Sorts a copy of a vector and compares to the expected result,
 * generated by a reference algorithm (std::stable_sort).
 */
template<typename Sort>
void check_vec(Sort sort, std::vector<tagged> input, order ord)
{
	auto expected = input;
	std::stable_sort(expected.begin(), expected.end());

	auto got = input;
	sort(got);

	if (ord == stable)
		TestEqual(tags(got), tags(expected));
	else
		TestEqual(keys(got), keys(expected));
}

//! ranges too short to have an interior
template<typename Sort>
void check_edges(Sort sort, order ord = stable)
{
	check_vec(sort, {}, ord);
	check_vec(sort, tag({ 1 }), ord);
	check_vec(sort, tag({ 1, 2 }), ord);
	check_vec(sort, tag({ 2, 1 }), ord);
	check_vec(sort, tag({ 1, 1 }), ord);
}

//! the arrangements an insertion sort takes different paths through
template<typename Sort>
void check_orders(Sort sort, order ord = stable)
{
	check_vec(sort, tag({ 1, 2, 3, 4, 5 }), ord);
	check_vec(sort, tag({ 5, 4, 3, 2, 1 }), ord);
	check_vec(sort, tag({ 5, 1, 4, 2, 3 }), ord);
	check_vec(sort, tag({ 1, 2, 5, 3, 4 }), ord);
	check_vec(sort, tag({ 2, 2, 2, 2, 2 }), ord);
	check_vec(sort, tag({ 2, 1, 2, 1, 2 }), ord);
	check_vec(sort, tag({ 1, 2, 1, 2, 1 }), ord);
}


//! how many distinct keys the sequences below are built from
constexpr int key_count = 3;
constexpr int key_positions = 4;

/*!
 * Calls \a visit on every sequence of [1..n] keys from an alphabet of \a k keys,
 * e.g. with k=2, n=3: { {0}, {1}, {0,0}, {0,1}, ..., {1,1,0}, {1,1,1} }.
 *
 * Each level of recursion appends one more key, so the sequence grows by a
 * position on the way down and is restored on the way back up.
 */
template<typename F>
void generate_sequences(int k, int n, const F& visit, std::vector<int> seq = {})
{
	visit(seq);

	if (n == 0)
		return;

	for (int key : range(k)) {
		seq.push_back(key);
		generate_sequences(k, n - 1, visit, seq);
		seq.pop_back();
	}
}

/*!
 * Tests every possible sequence of \a key_count distinct keys,
 * up to \a key_positions positions.
 *
 * This includes sequences with duplicate keys in every possible position,
 * so there's a high chance of detecting a stability bug.
 */
template<typename Sort>
void check_exhaustive(Sort sort, order ord = stable)
{
	generate_sequences(key_count, key_positions, [&](std::vector<int> const& seq) {
		check_vec(sort, tag(seq), ord);
	});
}

/*!
 * Creates a vector of \a elem_count random integers, with keys drawn
 * from \a key_count distinct values, so that a smaller value means
 * more duplicates.
 */
template<typename R>
auto make_random_vec(R& rng, size_t elem_count, int key_count = 20)
{
	std::vector<int> result;

	std::uniform_int_distribution d(0, key_count - 1);
	for (auto _ : range(elem_count))
		result.push_back(d(rng));
					
	return result;
}

constexpr size_t random_trial_count = 8;

//! long enough to reach paths the short cases never take
template<typename Sort>
void check_random(Sort sort, order ord = stable)
{
	std::mt19937 rng(0x5EED);
	for (auto _ : range(random_trial_count)) {
		std::vector<int> k = make_random_vec(rng, 200);
		check_vec(sort, tag(k), ord);
	}
}

} // namespace
} // namespace aw::test_sort

#define TestSortAlgorithm(name, ...) \
	Test(name##_edges)      { Checks { aw::test_sort::check_edges     (__VA_ARGS__); } } \
	Test(name##_orders)     { Checks { aw::test_sort::check_orders    (__VA_ARGS__); } } \
	Test(name##_exhaustive) { Checks { aw::test_sort::check_exhaustive(__VA_ARGS__); } } \
	Test(name##_random)     { Checks { aw::test_sort::check_random    (__VA_ARGS__); } }

#endif // aw_tests_algorithm_sort_tests_h
