RootPath = ../..
Sources = hpacker.cpp StringBank.cpp \
	  HPKTreeReader.cpp \
	  HPKListWriter.cpp HPKHtableWriter.cpp HPKTreeWriter.cpp \
	  ItdReader.cpp ItdPacker.cpp
Defines = 
Libraries = awplatform awcore
ProjectName = hpacker
Executable = true

include $(RootPath)/Rules.mk
