RootPath = ../..
Sources = test.cpp Canvas.cpp Drawer.cpp Window.cpp IrrEngine.cpp Style.cpp
Defines = HR_MODULE_GUI
Libraries = Irrlicht awcore
ProjectName = awgui
Executable = true

include $(RootPath)/Rules.mk
