RootPath = ../..
Sources = Canvas.cpp Drawer.cpp Window.cpp Style.cpp \
	  IrrEngine.cpp InputManager.cpp
Defines = AW_MODULE_GUI
Libraries = Irrlicht awcore
ProjectName = awgui
Executable = false

include $(RootPath)/Rules.mk
