RootPath = ../../..
SourceExt = c++
Sources = vector.c++ matrix.c++ matrix3.c++ angle.c++

Libraries    = awstring awplatform
ProjectName  = test_math
ProjectFlags = -fprofile-arcs -ftest-coverage
Executable   = true

include $(RootPath)/Rules.mk
