RootPath = ../../..
SourceExt = c++
Sources = functions.c++ bitmath.c++ angle.c++ orientation.c++ vector.c++ matrix.c++ matrix3.c++ matrix4.c++

Libraries    =
ProjectName  = test_math
ProjectFlags = #-fprofile-arcs -ftest-coverage
Executable   = true

include $(RootPath)/Rules.mk
