RootPath = ../../..
SourceExt = c++
Sources = renderer.c++ main.c++ camera_controller.c++ scene.c++
Defines =
Libraries = GL glfw stdc++fs awio awgraphics awobj awlog awdoc
ProjectName = rendertest
Executable  = true

include $(RootPath)/Rules.mk
