RootPath = ../../..
SourceExt = c++
Sources = obj_loader.c++ mtl_loader.c++ png_loader.c++
Defines = AW_MODULE_GRAPHICS #AW_MANUAL_TEST
Libraries = awio stdc++fs
ProjectName = awobj
Executable  = false

include $(RootPath)/Rules.mk
