RootPath = ../../..
SourceExt   = c++
Sources     = traits_promote.c++ traits_is_iterable.c++ \
variant.c++ queue.c++ flat_map.c++ string_view.c++ compint.c++
Libraries   =
ProjectName = test_types
ProjectFlags =
Executable = true

include $(RootPath)/Rules.mk
