RootPath = ../../..
SourceExt   = c++
Sources     = variant.c++ queue.c++ traits_promote.c++ string_view.c++
Libraries   =
ProjectName = test_types
ProjectFlags =
Executable = true

include $(RootPath)/Rules.mk
