RootPath = ../../..
Sources = native_file.cpp mmap_file.cpp file_stream.cpp main.cpp

Libraries    = awio awplatform stdc++fs
ProjectName  = test_io
ProjectFlags =
Executable   = true

include $(RootPath)/Rules.mk
