RootPath = ../../..
SourceExt = c++
Sources = on_scope_exit.c++ utf8toutf16.c++ MurmurHash3.c++
Libraries = awutils
ProjectName = test_utility
ProjectFlags = -fprofile-arcs -ftest-coverage
Executable = true

include $(RootPath)/Rules.mk
