RootPath = ../../..
SourceExt = c++
Sources = on_scope_exit.c++ utf8toutf16.c++ MurmurHash3.c++ functional.c++ static_object.c++ \
ranges_slice.c++ ranges_ipairs.c++ ranges_zip.c++
Libraries = awutils awplatform
ProjectName = test_utility
ProjectFlags = -fprofile-arcs -ftest-coverage
Executable = true

include $(RootPath)/Rules.mk
