RootPath = ../..
Objects = EntityManager.cpp EventManager.cpp SimplePathfinder.cpp World.cpp
Defines = HR_MODULE_GAME HR_MODULE_AI
Libraries = 
ProjectName = awgame
Executable = false

include $(RootPath)/Rules.mk
