RootPath = ../..
SourceExt = c++
Sources   = lexer.c++ parser.c++ writer.c++ utility.c++ document.c++
Defines   = AW_MODULE_DOC
Libraries =
ProjectName = doc
Executable = false

include $(RootPath)/Rules.mk
