RootPath = ../../..
Sources = to_string.cpp split.cpp split_iterator.cpp lazy_split.cpp \
join.cpp compose.cpp misc.cpp
Libraries = awstring awplatform
ProjectName = test_string
#ProjectFlags = -fprofile-arcs -ftest-coverage
Executable = true

include $(RootPath)/Rules.mk
