/*
 * hrengin game engine library
 * Copyright (C) 2013-2015  absurdworlds
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License, version 3
 * as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/>. 
 */
// This file is present only to supplement documentation generated by Doxygen
/*!
 * \mainpage hrengin Documentation
 * 
 * \section intro_sec What is hrengin?
 * hrengin (formerly hrEngine) is a general purpose game engine.
 * 
 * hrengin is based on modular architecture, that is, hrengin consists of several dynamically linked modules, which are intended to be easily replaceable (ideally without recompiling other modules).
 * 
 * Please note that hrengin is only a library and not a standalone game engine.
 */

//! Main namespace, contains everything else
namespace hrengin {
}
