RootPath = ../..
Sources = CameraNode.cpp VisNode.cpp EntityNode.cpp LightNode.cpp \
	  ConsoleGUI.cpp GUIListBox.cpp GuiManager.cpp GUITextBox.cpp GUIWindow.cpp \
	  InputManager.cpp RenderingDevice.cpp SceneManager.cpp VideoManager.cpp
Defines = HR_MODULE_GRAPHICS HR_MODULE_SCENE HR_MODULE_GUI
Libraries = Irrlicht
ProjectName = awgraphics
Executable = false

include $(RootPath)/Rules.mk
