RootPath = ../..
SourceExt = c++
Sources = gl/loader.c++ gl/gl_ext45.c++ gl3/shader.c++ gl3/program.c++
Defines = AW_MODULE_GRAPHICS
Libraries = GL
ProjectName = awgraphics
Executable  = false

include $(RootPath)/Rules.mk
