RootPath = ../..
SourceExt = c++
Sources = gl/loader.c++ gl/gl_api.c++ gl/enum_check.c++ \
gl3/shader.c++ gl3/program.c++ gl3/uniform.c++ gl3/model.c++ gl3/program_manager.c++
Defines = AW_MODULE_GRAPHICS
Libraries = GL
ProjectName = awgraphics
Executable  = false

include $(RootPath)/Rules.mk
