RootPath = ../..
Objects = CharacterStream.cpp BufferedStream.cpp \
	  ReadFile.cpp WriteFile.cpp posix/filesystem.cpp posix/Directory.cpp \
	  linux/time.cpp SFML/Window.cpp
Defines = HR_MODULE_PLATFORM HR_MODULE_IO
Libraries = sfml-window
ProjectName = awplatform
Executable = false

include $(RootPath)/Rules.mk
