RootPath = ../..
Sources = BulletPhysics.cpp CollisionPhantom.cpp DebugDrawer.cpp \
          PhysicsWorld.cpp RigidBody.cpp hrToBullet.cpp
Defines = HR_MODULE_PHYSICS
Libraries = BulletCollision BulletDynamics
ProjectName = awphysics
Executable = false

include $(RootPath)/Rules.mk
