RootPath = ../../..
SourceExt = c++
Sources = renderer.c++ main.c++ camera_controller.c++
Defines =
Libraries = GL glfw stdc++fs awio awgraphics awobj awlog
ProjectName = rendertest
Executable  = true

include $(RootPath)/Rules.mk
