RootPath = ../../..
SourceExt = c++
Sources = renderer.c++ main.c++ camera_controller.c++ scene.c++ test_gui.c++ \
imgui/imgui.cpp \
imgui/imgui_demo.cpp \
imgui/imgui_draw.cpp \
imgui/imgui_impl_glfw.cpp \
imgui/imgui_impl_opengl3.cpp \
imgui/imgui_tables.cpp \
imgui/imgui_widgets.cpp \

Defines =
Libraries = dl GL glfw stdc++fs awio awgraphics awobj awlog awdoc
ProjectName = rendertest
Executable  = true

include $(RootPath)/Rules.mk
