RootPath = ../../..
SourceExt = c++
Sources = renderer.c++
Defines =
Libraries = GL sfml-system sfml-window stdc++fs awio awgraphics awobj
ProjectName = rendertest
Executable  = true

include $(RootPath)/Rules.mk
