RootPath = ../../..
SourceExt = c++
Sources = split.c++ join.c++ common_prefix.c++
Libraries =
ProjectName = test_algo
ProjectFlags = #-fprofile-arcs -ftest-coverage
Executable = true

include $(RootPath)/Rules.mk
