RootPath = ../..
Sources  = posix/file.cpp posix/mmap.cpp
#Sources = win32/file.cpp win32/mmap.cpp win32/winapi_category.cpp win32/error_codes.cpp
Defines  = AW_MODULE_IO
Libraries =
ProjectName = awio
Executable = false

include $(RootPath)/Rules.mk
