/*
 * Copyright (C) 2014  absurdworlds
 *
 * License LGPLv3 or later:
 * GNU Lesser GPL version 3 <http://gnu.org/licenses/lgpl-3.0.html>
 * This is free software: you are free to change and redistribute it.
 * There is NO WARRANTY, to the extent permitted by law.
 */
#ifndef aw_meta_pp_for_each_h
#define aw_meta_pp_for_each_h
#include "macro.h"
#include "nargs.h"



#define FE_1(OP,  DO, X, ...)  DO(X)
#define FE_2(OP,  DO, X, ...)  OP(DO(X), FE_1(OP,  DO, __VA_ARGS__))
#define FE_3(OP,  DO, X, ...)  OP(DO(X), FE_2(OP,  DO, __VA_ARGS__))
#define FE_4(OP,  DO, X, ...)  OP(DO(X), FE_3(OP,  DO, __VA_ARGS__))
#define FE_5(OP,  DO, X, ...)  OP(DO(X), FE_4(OP,  DO, __VA_ARGS__))
#define FE_6(OP,  DO, X, ...)  OP(DO(X), FE_5(OP,  DO, __VA_ARGS__))
#define FE_7(OP,  DO, X, ...)  OP(DO(X), FE_6(OP,  DO, __VA_ARGS__))
#define FE_8(OP,  DO, X, ...)  OP(DO(X), FE_7(OP,  DO, __VA_ARGS__))
#define FE_9(OP,  DO, X, ...)  OP(DO(X), FE_8(OP,  DO, __VA_ARGS__))
#define FE_10(OP, DO, X, ...)  OP(DO(X), FE_9(OP,  DO, __VA_ARGS__))
#define FE_11(OP, DO, X, ...)  OP(DO(X), FE_10(OP, DO, __VA_ARGS__))
#define FE_12(OP, DO, X, ...)  OP(DO(X), FE_11(OP, DO, __VA_ARGS__))
#define FE_13(OP, DO, X, ...)  OP(DO(X), FE_12(OP, DO, __VA_ARGS__))
#define FE_14(OP, DO, X, ...)  OP(DO(X), FE_13(OP, DO, __VA_ARGS__))
#define FE_15(OP, DO, X, ...)  OP(DO(X), FE_14(OP, DO, __VA_ARGS__))
#define FE_16(OP, DO, X, ...)  OP(DO(X), FE_15(OP, DO, __VA_ARGS__))
#define FE_17(OP, DO, X, ...)  OP(DO(X), FE_16(OP, DO, __VA_ARGS__))
#define FE_18(OP, DO, X, ...)  OP(DO(X), FE_17(OP, DO, __VA_ARGS__))
#define FE_19(OP, DO, X, ...)  OP(DO(X), FE_18(OP, DO, __VA_ARGS__))
#define FE_20(OP, DO, X, ...)  OP(DO(X), FE_19(OP, DO, __VA_ARGS__))
#define FE_21(OP, DO, X, ...)  OP(DO(X), FE_20(OP, DO, __VA_ARGS__))
#define FE_22(OP, DO, X, ...)  OP(DO(X), FE_21(OP, DO, __VA_ARGS__))
#define FE_23(OP, DO, X, ...)  OP(DO(X), FE_22(OP, DO, __VA_ARGS__))
#define FE_24(OP, DO, X, ...)  OP(DO(X), FE_23(OP, DO, __VA_ARGS__))
#define FE_25(OP, DO, X, ...)  OP(DO(X), FE_24(OP, DO, __VA_ARGS__))
#define FE_26(OP, DO, X, ...)  OP(DO(X), FE_25(OP, DO, __VA_ARGS__))
#define FE_27(OP, DO, X, ...)  OP(DO(X), FE_26(OP, DO, __VA_ARGS__))
#define FE_28(OP, DO, X, ...)  OP(DO(X), FE_27(OP, DO, __VA_ARGS__))
#define FE_29(OP, DO, X, ...)  OP(DO(X), FE_28(OP, DO, __VA_ARGS__))
#define FE_30(OP, DO, X, ...)  OP(DO(X), FE_29(OP, DO, __VA_ARGS__))
#define FE_31(OP, DO, X, ...)  OP(DO(X), FE_30(OP, DO, __VA_ARGS__))
#define FE_32(OP, DO, X, ...)  OP(DO(X), FE_31(OP, DO, __VA_ARGS__))
#define FE_33(OP, DO, X, ...)  OP(DO(X), FE_32(OP, DO, __VA_ARGS__))
#define FE_34(OP, DO, X, ...)  OP(DO(X), FE_33(OP, DO, __VA_ARGS__))
#define FE_35(OP, DO, X, ...)  OP(DO(X), FE_34(OP, DO, __VA_ARGS__))
#define FE_36(OP, DO, X, ...)  OP(DO(X), FE_35(OP, DO, __VA_ARGS__))
#define FE_37(OP, DO, X, ...)  OP(DO(X), FE_36(OP, DO, __VA_ARGS__))
#define FE_38(OP, DO, X, ...)  OP(DO(X), FE_37(OP, DO, __VA_ARGS__))
#define FE_39(OP, DO, X, ...)  OP(DO(X), FE_38(OP, DO, __VA_ARGS__))
#define FE_40(OP, DO, X, ...)  OP(DO(X), FE_39(OP, DO, __VA_ARGS__))
#define FE_41(OP, DO, X, ...)  OP(DO(X), FE_40(OP, DO, __VA_ARGS__))
#define FE_42(OP, DO, X, ...)  OP(DO(X), FE_41(OP, DO, __VA_ARGS__))
#define FE_43(OP, DO, X, ...)  OP(DO(X), FE_42(OP, DO, __VA_ARGS__))
#define FE_44(OP, DO, X, ...)  OP(DO(X), FE_43(OP, DO, __VA_ARGS__))
#define FE_45(OP, DO, X, ...)  OP(DO(X), FE_44(OP, DO, __VA_ARGS__))
#define FE_46(OP, DO, X, ...)  OP(DO(X), FE_45(OP, DO, __VA_ARGS__))
#define FE_47(OP, DO, X, ...)  OP(DO(X), FE_46(OP, DO, __VA_ARGS__))
#define FE_48(OP, DO, X, ...)  OP(DO(X), FE_47(OP, DO, __VA_ARGS__))
#define FE_49(OP, DO, X, ...)  OP(DO(X), FE_48(OP, DO, __VA_ARGS__))
#define FE_50(OP, DO, X, ...)  OP(DO(X), FE_49(OP, DO, __VA_ARGS__))
#define FE_51(OP, DO, X, ...)  OP(DO(X), FE_50(OP, DO, __VA_ARGS__))
#define FE_52(OP, DO, X, ...)  OP(DO(X), FE_51(OP, DO, __VA_ARGS__))
#define FE_53(OP, DO, X, ...)  OP(DO(X), FE_52(OP, DO, __VA_ARGS__))
#define FE_54(OP, DO, X, ...)  OP(DO(X), FE_53(OP, DO, __VA_ARGS__))
#define FE_55(OP, DO, X, ...)  OP(DO(X), FE_54(OP, DO, __VA_ARGS__))
#define FE_56(OP, DO, X, ...)  OP(DO(X), FE_55(OP, DO, __VA_ARGS__))
#define FE_57(OP, DO, X, ...)  OP(DO(X), FE_56(OP, DO, __VA_ARGS__))
#define FE_58(OP, DO, X, ...)  OP(DO(X), FE_57(OP, DO, __VA_ARGS__))
#define FE_59(OP, DO, X, ...)  OP(DO(X), FE_58(OP, DO, __VA_ARGS__))
#define FE_60(OP, DO, X, ...)  OP(DO(X), FE_59(OP, DO, __VA_ARGS__))
#define FE_61(OP, DO, X, ...)  OP(DO(X), FE_60(OP, DO, __VA_ARGS__))
#define FE_62(OP, DO, X, ...)  OP(DO(X), FE_61(OP, DO, __VA_ARGS__))
#define FE_63(OP, DO, X, ...)  OP(DO(X), FE_62(OP, DO, __VA_ARGS__))
#define FE_64(OP, DO, X, ...)  OP(DO(X), FE_63(OP, DO, __VA_ARGS__))
#define FE_65(OP, DO, X, ...)  OP(DO(X), FE_64(OP, DO, __VA_ARGS__))
#define FE_66(OP, DO, X, ...)  OP(DO(X), FE_65(OP, DO, __VA_ARGS__))
#define FE_67(OP, DO, X, ...)  OP(DO(X), FE_66(OP, DO, __VA_ARGS__))
#define FE_68(OP, DO, X, ...)  OP(DO(X), FE_67(OP, DO, __VA_ARGS__))
#define FE_69(OP, DO, X, ...)  OP(DO(X), FE_68(OP, DO, __VA_ARGS__))
#define FE_70(OP, DO, X, ...)  OP(DO(X), FE_69(OP, DO, __VA_ARGS__))
#define FE_71(OP, DO, X, ...)  OP(DO(X), FE_70(OP, DO, __VA_ARGS__))
#define FE_72(OP, DO, X, ...)  OP(DO(X), FE_71(OP, DO, __VA_ARGS__))
#define FE_73(OP, DO, X, ...)  OP(DO(X), FE_72(OP, DO, __VA_ARGS__))
#define FE_74(OP, DO, X, ...)  OP(DO(X), FE_73(OP, DO, __VA_ARGS__))
#define FE_75(OP, DO, X, ...)  OP(DO(X), FE_74(OP, DO, __VA_ARGS__))
#define FE_76(OP, DO, X, ...)  OP(DO(X), FE_75(OP, DO, __VA_ARGS__))
#define FE_77(OP, DO, X, ...)  OP(DO(X), FE_76(OP, DO, __VA_ARGS__))
#define FE_78(OP, DO, X, ...)  OP(DO(X), FE_77(OP, DO, __VA_ARGS__))
#define FE_79(OP, DO, X, ...)  OP(DO(X), FE_78(OP, DO, __VA_ARGS__))
#define FE_80(OP, DO, X, ...)  OP(DO(X), FE_79(OP, DO, __VA_ARGS__))
#define FE_81(OP, DO, X, ...)  OP(DO(X), FE_80(OP, DO, __VA_ARGS__))
#define FE_82(OP, DO, X, ...)  OP(DO(X), FE_81(OP, DO, __VA_ARGS__))
#define FE_83(OP, DO, X, ...)  OP(DO(X), FE_82(OP, DO, __VA_ARGS__))
#define FE_84(OP, DO, X, ...)  OP(DO(X), FE_83(OP, DO, __VA_ARGS__))
#define FE_85(OP, DO, X, ...)  OP(DO(X), FE_84(OP, DO, __VA_ARGS__))
#define FE_86(OP, DO, X, ...)  OP(DO(X), FE_85(OP, DO, __VA_ARGS__))
#define FE_87(OP, DO, X, ...)  OP(DO(X), FE_86(OP, DO, __VA_ARGS__))
#define FE_88(OP, DO, X, ...)  OP(DO(X), FE_87(OP, DO, __VA_ARGS__))
#define FE_89(OP, DO, X, ...)  OP(DO(X), FE_88(OP, DO, __VA_ARGS__))
#define FE_90(OP, DO, X, ...)  OP(DO(X), FE_89(OP, DO, __VA_ARGS__))
#define FE_91(OP, DO, X, ...)  OP(DO(X), FE_90(OP, DO, __VA_ARGS__))
#define FE_92(OP, DO, X, ...)  OP(DO(X), FE_91(OP, DO, __VA_ARGS__))
#define FE_93(OP, DO, X, ...)  OP(DO(X), FE_92(OP, DO, __VA_ARGS__))
#define FE_94(OP, DO, X, ...)  OP(DO(X), FE_93(OP, DO, __VA_ARGS__))
#define FE_95(OP, DO, X, ...)  OP(DO(X), FE_94(OP, DO, __VA_ARGS__))
#define FE_96(OP, DO, X, ...)  OP(DO(X), FE_95(OP, DO, __VA_ARGS__))
#define FE_97(OP, DO, X, ...)  OP(DO(X), FE_96(OP, DO, __VA_ARGS__))
#define FE_98(OP, DO, X, ...)  OP(DO(X), FE_97(OP, DO, __VA_ARGS__))
#define FE_99(OP, DO, X, ...)  OP(DO(X), FE_98(OP, DO, __VA_ARGS__))
#define FE_100(OP, DO, X, ...) OP(DO(X), FE_99(OP, DO, __VA_ARGS__))

#define FOR_EACH(OP,NAME,...) \
	APPLY( CONCAT( FE_, N_ARGS(__VA_ARGS__)), OP, NAME, __VA_ARGS__)

#define FOLD(OP,...) \
	FOR_EACH( OP, EXPAND, __VA_ARGS__)
#endif//aw_meta_pp_for_each_h
