/*
 * Copyright (C) 2014  absurdworlds
 *
 * License LGPLv3 or later:
 * GNU Lesser GPL version 3 <http://gnu.org/licenses/lgpl-3.0.html>
 * This is free software: you are free to change and redistribute it.
 * There is NO WARRANTY, to the extent permitted by law.
 */
#ifndef aw_meta_pp_foldr_h
#define aw_meta_pp_foldr_h
#include "apply_n.h"

#define AW_FR_1(OP,  DO, X, ...)  DO(X)
#define AW_FR_2(OP,  DO, X, ...)  OP(DO(X), AW_FR_1(OP,  DO, __VA_ARGS__))
#define AW_FR_3(OP,  DO, X, ...)  OP(DO(X), AW_FR_2(OP,  DO, __VA_ARGS__))
#define AW_FR_4(OP,  DO, X, ...)  OP(DO(X), AW_FR_3(OP,  DO, __VA_ARGS__))
#define AW_FR_5(OP,  DO, X, ...)  OP(DO(X), AW_FR_4(OP,  DO, __VA_ARGS__))
#define AW_FR_6(OP,  DO, X, ...)  OP(DO(X), AW_FR_5(OP,  DO, __VA_ARGS__))
#define AW_FR_7(OP,  DO, X, ...)  OP(DO(X), AW_FR_6(OP,  DO, __VA_ARGS__))
#define AW_FR_8(OP,  DO, X, ...)  OP(DO(X), AW_FR_7(OP,  DO, __VA_ARGS__))
#define AW_FR_9(OP,  DO, X, ...)  OP(DO(X), AW_FR_8(OP,  DO, __VA_ARGS__))
#define AW_FR_10(OP, DO, X, ...)  OP(DO(X), AW_FR_9(OP,  DO, __VA_ARGS__))
#define AW_FR_11(OP, DO, X, ...)  OP(DO(X), AW_FR_10(OP, DO, __VA_ARGS__))
#define AW_FR_12(OP, DO, X, ...)  OP(DO(X), AW_FR_11(OP, DO, __VA_ARGS__))
#define AW_FR_13(OP, DO, X, ...)  OP(DO(X), AW_FR_12(OP, DO, __VA_ARGS__))
#define AW_FR_14(OP, DO, X, ...)  OP(DO(X), AW_FR_13(OP, DO, __VA_ARGS__))
#define AW_FR_15(OP, DO, X, ...)  OP(DO(X), AW_FR_14(OP, DO, __VA_ARGS__))
#define AW_FR_16(OP, DO, X, ...)  OP(DO(X), AW_FR_15(OP, DO, __VA_ARGS__))
#define AW_FR_17(OP, DO, X, ...)  OP(DO(X), AW_FR_16(OP, DO, __VA_ARGS__))
#define AW_FR_18(OP, DO, X, ...)  OP(DO(X), AW_FR_17(OP, DO, __VA_ARGS__))
#define AW_FR_19(OP, DO, X, ...)  OP(DO(X), AW_FR_18(OP, DO, __VA_ARGS__))
#define AW_FR_20(OP, DO, X, ...)  OP(DO(X), AW_FR_19(OP, DO, __VA_ARGS__))
#define AW_FR_21(OP, DO, X, ...)  OP(DO(X), AW_FR_20(OP, DO, __VA_ARGS__))
#define AW_FR_22(OP, DO, X, ...)  OP(DO(X), AW_FR_21(OP, DO, __VA_ARGS__))
#define AW_FR_23(OP, DO, X, ...)  OP(DO(X), AW_FR_22(OP, DO, __VA_ARGS__))
#define AW_FR_24(OP, DO, X, ...)  OP(DO(X), AW_FR_23(OP, DO, __VA_ARGS__))
#define AW_FR_25(OP, DO, X, ...)  OP(DO(X), AW_FR_24(OP, DO, __VA_ARGS__))
#define AW_FR_26(OP, DO, X, ...)  OP(DO(X), AW_FR_25(OP, DO, __VA_ARGS__))
#define AW_FR_27(OP, DO, X, ...)  OP(DO(X), AW_FR_26(OP, DO, __VA_ARGS__))
#define AW_FR_28(OP, DO, X, ...)  OP(DO(X), AW_FR_27(OP, DO, __VA_ARGS__))
#define AW_FR_29(OP, DO, X, ...)  OP(DO(X), AW_FR_28(OP, DO, __VA_ARGS__))
#define AW_FR_30(OP, DO, X, ...)  OP(DO(X), AW_FR_29(OP, DO, __VA_ARGS__))
#define AW_FR_31(OP, DO, X, ...)  OP(DO(X), AW_FR_30(OP, DO, __VA_ARGS__))
#define AW_FR_32(OP, DO, X, ...)  OP(DO(X), AW_FR_31(OP, DO, __VA_ARGS__))
#define AW_FR_33(OP, DO, X, ...)  OP(DO(X), AW_FR_32(OP, DO, __VA_ARGS__))
#define AW_FR_34(OP, DO, X, ...)  OP(DO(X), AW_FR_33(OP, DO, __VA_ARGS__))
#define AW_FR_35(OP, DO, X, ...)  OP(DO(X), AW_FR_34(OP, DO, __VA_ARGS__))
#define AW_FR_36(OP, DO, X, ...)  OP(DO(X), AW_FR_35(OP, DO, __VA_ARGS__))
#define AW_FR_37(OP, DO, X, ...)  OP(DO(X), AW_FR_36(OP, DO, __VA_ARGS__))
#define AW_FR_38(OP, DO, X, ...)  OP(DO(X), AW_FR_37(OP, DO, __VA_ARGS__))
#define AW_FR_39(OP, DO, X, ...)  OP(DO(X), AW_FR_38(OP, DO, __VA_ARGS__))
#define AW_FR_40(OP, DO, X, ...)  OP(DO(X), AW_FR_39(OP, DO, __VA_ARGS__))
#define AW_FR_41(OP, DO, X, ...)  OP(DO(X), AW_FR_40(OP, DO, __VA_ARGS__))
#define AW_FR_42(OP, DO, X, ...)  OP(DO(X), AW_FR_41(OP, DO, __VA_ARGS__))
#define AW_FR_43(OP, DO, X, ...)  OP(DO(X), AW_FR_42(OP, DO, __VA_ARGS__))
#define AW_FR_44(OP, DO, X, ...)  OP(DO(X), AW_FR_43(OP, DO, __VA_ARGS__))
#define AW_FR_45(OP, DO, X, ...)  OP(DO(X), AW_FR_44(OP, DO, __VA_ARGS__))
#define AW_FR_46(OP, DO, X, ...)  OP(DO(X), AW_FR_45(OP, DO, __VA_ARGS__))
#define AW_FR_47(OP, DO, X, ...)  OP(DO(X), AW_FR_46(OP, DO, __VA_ARGS__))
#define AW_FR_48(OP, DO, X, ...)  OP(DO(X), AW_FR_47(OP, DO, __VA_ARGS__))
#define AW_FR_49(OP, DO, X, ...)  OP(DO(X), AW_FR_48(OP, DO, __VA_ARGS__))
#define AW_FR_50(OP, DO, X, ...)  OP(DO(X), AW_FR_49(OP, DO, __VA_ARGS__))
#define AW_FR_51(OP, DO, X, ...)  OP(DO(X), AW_FR_50(OP, DO, __VA_ARGS__))
#define AW_FR_52(OP, DO, X, ...)  OP(DO(X), AW_FR_51(OP, DO, __VA_ARGS__))
#define AW_FR_53(OP, DO, X, ...)  OP(DO(X), AW_FR_52(OP, DO, __VA_ARGS__))
#define AW_FR_54(OP, DO, X, ...)  OP(DO(X), AW_FR_53(OP, DO, __VA_ARGS__))
#define AW_FR_55(OP, DO, X, ...)  OP(DO(X), AW_FR_54(OP, DO, __VA_ARGS__))
#define AW_FR_56(OP, DO, X, ...)  OP(DO(X), AW_FR_55(OP, DO, __VA_ARGS__))
#define AW_FR_57(OP, DO, X, ...)  OP(DO(X), AW_FR_56(OP, DO, __VA_ARGS__))
#define AW_FR_58(OP, DO, X, ...)  OP(DO(X), AW_FR_57(OP, DO, __VA_ARGS__))
#define AW_FR_59(OP, DO, X, ...)  OP(DO(X), AW_FR_58(OP, DO, __VA_ARGS__))
#define AW_FR_60(OP, DO, X, ...)  OP(DO(X), AW_FR_59(OP, DO, __VA_ARGS__))
#define AW_FR_61(OP, DO, X, ...)  OP(DO(X), AW_FR_60(OP, DO, __VA_ARGS__))
#define AW_FR_62(OP, DO, X, ...)  OP(DO(X), AW_FR_61(OP, DO, __VA_ARGS__))
#define AW_FR_63(OP, DO, X, ...)  OP(DO(X), AW_FR_62(OP, DO, __VA_ARGS__))
#define AW_FR_64(OP, DO, X, ...)  OP(DO(X), AW_FR_63(OP, DO, __VA_ARGS__))
#define AW_FR_65(OP, DO, X, ...)  OP(DO(X), AW_FR_64(OP, DO, __VA_ARGS__))
#define AW_FR_66(OP, DO, X, ...)  OP(DO(X), AW_FR_65(OP, DO, __VA_ARGS__))
#define AW_FR_67(OP, DO, X, ...)  OP(DO(X), AW_FR_66(OP, DO, __VA_ARGS__))
#define AW_FR_68(OP, DO, X, ...)  OP(DO(X), AW_FR_67(OP, DO, __VA_ARGS__))
#define AW_FR_69(OP, DO, X, ...)  OP(DO(X), AW_FR_68(OP, DO, __VA_ARGS__))
#define AW_FR_70(OP, DO, X, ...)  OP(DO(X), AW_FR_69(OP, DO, __VA_ARGS__))
#define AW_FR_71(OP, DO, X, ...)  OP(DO(X), AW_FR_70(OP, DO, __VA_ARGS__))
#define AW_FR_72(OP, DO, X, ...)  OP(DO(X), AW_FR_71(OP, DO, __VA_ARGS__))
#define AW_FR_73(OP, DO, X, ...)  OP(DO(X), AW_FR_72(OP, DO, __VA_ARGS__))
#define AW_FR_74(OP, DO, X, ...)  OP(DO(X), AW_FR_73(OP, DO, __VA_ARGS__))
#define AW_FR_75(OP, DO, X, ...)  OP(DO(X), AW_FR_74(OP, DO, __VA_ARGS__))
#define AW_FR_76(OP, DO, X, ...)  OP(DO(X), AW_FR_75(OP, DO, __VA_ARGS__))
#define AW_FR_77(OP, DO, X, ...)  OP(DO(X), AW_FR_76(OP, DO, __VA_ARGS__))
#define AW_FR_78(OP, DO, X, ...)  OP(DO(X), AW_FR_77(OP, DO, __VA_ARGS__))
#define AW_FR_79(OP, DO, X, ...)  OP(DO(X), AW_FR_78(OP, DO, __VA_ARGS__))
#define AW_FR_80(OP, DO, X, ...)  OP(DO(X), AW_FR_79(OP, DO, __VA_ARGS__))
#define AW_FR_81(OP, DO, X, ...)  OP(DO(X), AW_FR_80(OP, DO, __VA_ARGS__))
#define AW_FR_82(OP, DO, X, ...)  OP(DO(X), AW_FR_81(OP, DO, __VA_ARGS__))
#define AW_FR_83(OP, DO, X, ...)  OP(DO(X), AW_FR_82(OP, DO, __VA_ARGS__))
#define AW_FR_84(OP, DO, X, ...)  OP(DO(X), AW_FR_83(OP, DO, __VA_ARGS__))
#define AW_FR_85(OP, DO, X, ...)  OP(DO(X), AW_FR_84(OP, DO, __VA_ARGS__))
#define AW_FR_86(OP, DO, X, ...)  OP(DO(X), AW_FR_85(OP, DO, __VA_ARGS__))
#define AW_FR_87(OP, DO, X, ...)  OP(DO(X), AW_FR_86(OP, DO, __VA_ARGS__))
#define AW_FR_88(OP, DO, X, ...)  OP(DO(X), AW_FR_87(OP, DO, __VA_ARGS__))
#define AW_FR_89(OP, DO, X, ...)  OP(DO(X), AW_FR_88(OP, DO, __VA_ARGS__))
#define AW_FR_90(OP, DO, X, ...)  OP(DO(X), AW_FR_89(OP, DO, __VA_ARGS__))
#define AW_FR_91(OP, DO, X, ...)  OP(DO(X), AW_FR_90(OP, DO, __VA_ARGS__))
#define AW_FR_92(OP, DO, X, ...)  OP(DO(X), AW_FR_91(OP, DO, __VA_ARGS__))
#define AW_FR_93(OP, DO, X, ...)  OP(DO(X), AW_FR_92(OP, DO, __VA_ARGS__))
#define AW_FR_94(OP, DO, X, ...)  OP(DO(X), AW_FR_93(OP, DO, __VA_ARGS__))
#define AW_FR_95(OP, DO, X, ...)  OP(DO(X), AW_FR_94(OP, DO, __VA_ARGS__))
#define AW_FR_96(OP, DO, X, ...)  OP(DO(X), AW_FR_95(OP, DO, __VA_ARGS__))
#define AW_FR_97(OP, DO, X, ...)  OP(DO(X), AW_FR_96(OP, DO, __VA_ARGS__))
#define AW_FR_98(OP, DO, X, ...)  OP(DO(X), AW_FR_97(OP, DO, __VA_ARGS__))
#define AW_FR_99(OP, DO, X, ...)  OP(DO(X), AW_FR_98(OP, DO, __VA_ARGS__))
#define AW_FR_100(OP, DO, X, ...) OP(DO(X), AW_FR_99(OP, DO, __VA_ARGS__))

#define AW_FOLD_RIGHT(OP,NAME,...) \
	AW_APPLY( AW_SUFFIX_N(AW_FR_,__VA_ARGS__), OP, NAME, __VA_ARGS__)

#define AW_FOLDR(OP,...) \
	AW_FOLD_RIGHT( OP, AW_EXPAND, __VA_ARGS__)

#define AW_FOREACH(FUNC,...) \
	AW_FOLD_RIGHT( AW_EXPAND, FUNC, __VA_ARGS__)
#endif//aw_meta_pp_foldr_h
