/*
 * Copyright (C) 2014  absurdworlds
 *
 * License LGPLv3 or later:
 * GNU Lesser GPL version 3 <http://gnu.org/licenses/lgpl-3.0.html>
 * This is free software: you are free to change and redistribute it.
 * There is NO WARRANTY, to the extent permitted by law.
 */
#ifndef aw_meta_pp_foldl_h
#define aw_meta_pp_foldl_h
#include "reverse.h"

#define AW_FL_1(OP,  DO, X, ...)  DO(X)
#define AW_FL_2(OP,  DO, X, ...)  OP(AW_FL_1(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_3(OP,  DO, X, ...)  OP(AW_FL_2(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_4(OP,  DO, X, ...)  OP(AW_FL_3(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_5(OP,  DO, X, ...)  OP(AW_FL_4(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_6(OP,  DO, X, ...)  OP(AW_FL_5(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_7(OP,  DO, X, ...)  OP(AW_FL_6(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_8(OP,  DO, X, ...)  OP(AW_FL_7(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_9(OP,  DO, X, ...)  OP(AW_FL_8(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_10(OP, DO, X, ...)  OP(AW_FL_9(OP,  DO, __VA_ARGS__), DO(X))
#define AW_FL_11(OP, DO, X, ...)  OP(AW_FL_10(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_12(OP, DO, X, ...)  OP(AW_FL_11(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_13(OP, DO, X, ...)  OP(AW_FL_12(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_14(OP, DO, X, ...)  OP(AW_FL_13(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_15(OP, DO, X, ...)  OP(AW_FL_14(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_16(OP, DO, X, ...)  OP(AW_FL_15(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_17(OP, DO, X, ...)  OP(AW_FL_16(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_18(OP, DO, X, ...)  OP(AW_FL_17(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_19(OP, DO, X, ...)  OP(AW_FL_18(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_20(OP, DO, X, ...)  OP(AW_FL_19(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_21(OP, DO, X, ...)  OP(AW_FL_20(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_22(OP, DO, X, ...)  OP(AW_FL_21(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_23(OP, DO, X, ...)  OP(AW_FL_22(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_24(OP, DO, X, ...)  OP(AW_FL_23(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_25(OP, DO, X, ...)  OP(AW_FL_24(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_26(OP, DO, X, ...)  OP(AW_FL_25(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_27(OP, DO, X, ...)  OP(AW_FL_26(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_28(OP, DO, X, ...)  OP(AW_FL_27(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_29(OP, DO, X, ...)  OP(AW_FL_28(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_30(OP, DO, X, ...)  OP(AW_FL_29(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_31(OP, DO, X, ...)  OP(AW_FL_30(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_32(OP, DO, X, ...)  OP(AW_FL_31(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_33(OP, DO, X, ...)  OP(AW_FL_32(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_34(OP, DO, X, ...)  OP(AW_FL_33(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_35(OP, DO, X, ...)  OP(AW_FL_34(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_36(OP, DO, X, ...)  OP(AW_FL_35(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_37(OP, DO, X, ...)  OP(AW_FL_36(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_38(OP, DO, X, ...)  OP(AW_FL_37(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_39(OP, DO, X, ...)  OP(AW_FL_38(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_40(OP, DO, X, ...)  OP(AW_FL_39(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_41(OP, DO, X, ...)  OP(AW_FL_40(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_42(OP, DO, X, ...)  OP(AW_FL_41(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_43(OP, DO, X, ...)  OP(AW_FL_42(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_44(OP, DO, X, ...)  OP(AW_FL_43(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_45(OP, DO, X, ...)  OP(AW_FL_44(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_46(OP, DO, X, ...)  OP(AW_FL_45(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_47(OP, DO, X, ...)  OP(AW_FL_46(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_48(OP, DO, X, ...)  OP(AW_FL_47(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_49(OP, DO, X, ...)  OP(AW_FL_48(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_50(OP, DO, X, ...)  OP(AW_FL_49(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_51(OP, DO, X, ...)  OP(AW_FL_50(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_52(OP, DO, X, ...)  OP(AW_FL_51(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_53(OP, DO, X, ...)  OP(AW_FL_52(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_54(OP, DO, X, ...)  OP(AW_FL_53(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_55(OP, DO, X, ...)  OP(AW_FL_54(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_56(OP, DO, X, ...)  OP(AW_FL_55(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_57(OP, DO, X, ...)  OP(AW_FL_56(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_58(OP, DO, X, ...)  OP(AW_FL_57(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_59(OP, DO, X, ...)  OP(AW_FL_58(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_60(OP, DO, X, ...)  OP(AW_FL_59(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_61(OP, DO, X, ...)  OP(AW_FL_60(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_62(OP, DO, X, ...)  OP(AW_FL_61(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_63(OP, DO, X, ...)  OP(AW_FL_62(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_64(OP, DO, X, ...)  OP(AW_FL_63(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_65(OP, DO, X, ...)  OP(AW_FL_64(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_66(OP, DO, X, ...)  OP(AW_FL_65(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_67(OP, DO, X, ...)  OP(AW_FL_66(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_68(OP, DO, X, ...)  OP(AW_FL_67(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_69(OP, DO, X, ...)  OP(AW_FL_68(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_70(OP, DO, X, ...)  OP(AW_FL_69(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_71(OP, DO, X, ...)  OP(AW_FL_70(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_72(OP, DO, X, ...)  OP(AW_FL_71(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_73(OP, DO, X, ...)  OP(AW_FL_72(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_74(OP, DO, X, ...)  OP(AW_FL_73(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_75(OP, DO, X, ...)  OP(AW_FL_74(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_76(OP, DO, X, ...)  OP(AW_FL_75(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_77(OP, DO, X, ...)  OP(AW_FL_76(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_78(OP, DO, X, ...)  OP(AW_FL_77(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_79(OP, DO, X, ...)  OP(AW_FL_78(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_80(OP, DO, X, ...)  OP(AW_FL_79(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_81(OP, DO, X, ...)  OP(AW_FL_80(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_82(OP, DO, X, ...)  OP(AW_FL_81(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_83(OP, DO, X, ...)  OP(AW_FL_82(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_84(OP, DO, X, ...)  OP(AW_FL_83(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_85(OP, DO, X, ...)  OP(AW_FL_84(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_86(OP, DO, X, ...)  OP(AW_FL_85(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_87(OP, DO, X, ...)  OP(AW_FL_86(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_88(OP, DO, X, ...)  OP(AW_FL_87(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_89(OP, DO, X, ...)  OP(AW_FL_88(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_90(OP, DO, X, ...)  OP(AW_FL_89(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_91(OP, DO, X, ...)  OP(AW_FL_90(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_92(OP, DO, X, ...)  OP(AW_FL_91(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_93(OP, DO, X, ...)  OP(AW_FL_92(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_94(OP, DO, X, ...)  OP(AW_FL_93(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_95(OP, DO, X, ...)  OP(AW_FL_94(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_96(OP, DO, X, ...)  OP(AW_FL_95(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_97(OP, DO, X, ...)  OP(AW_FL_96(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_98(OP, DO, X, ...)  OP(AW_FL_97(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_99(OP, DO, X, ...)  OP(AW_FL_98(OP, DO, __VA_ARGS__), DO(X))
#define AW_FL_100(OP, DO, X, ...) OP(AW_FL_99(OP, DO, __VA_ARGS__), DO(X))

#define AW_FOLD_LEFT(OP,NAME,...) \
	AW_APPLY( AW_SUFFIX_N(AW_FL_,__VA_ARGS__), OP, NAME, AW_REVERSE(__VA_ARGS__))

#define AW_FOLDL(OP,...) \
	AW_FOLD_LEFT( OP, AW_IDENTITY, __VA_ARGS__)
#endif//aw_meta_pp_foldl_h
