RootPath = ../../..
Sources = to_string.cpp split.cpp join.cpp compose.cpp misc.cpp
Libraries = awstring
ProjectName = test_string
ProjectFlags = -fprofile-arcs -ftest-coverage
Executable = true

include $(RootPath)/Rules.mk
