RootPath = ../../..
SourceExt = c++
Sources = reader.c++
# Defines = AW_MODULE_UI
Libraries = awlog awutils awio awstring awdoc stdc++fs
ProjectName = doc_example
Executable = true

include $(RootPath)/Rules.mk
